CREATE DATABASE LABOIL;

USE LABOIL;

CREATE TABLE CITIZEN (
  USER_ID CHAR(36) PRIMARY KEY,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  TOWN VARCHAR(36) NOT NULL,
  PHONE_NUMBER INT(20),
  BIRTH_DATE VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  REG_NAT VARCHAR(100) NOT NULL,
  GENDER CHAR(1) NOT NULL,
  BIRTH_PLACE VARCHAR(30) NOT NULL,
  ENABLED BOOLEAN not null default true,
  COMPANY_VAT_NR CHAR(36)
);

CREATE TABLE EMPLOYEE (
  USER_ID CHAR(36) PRIMARY KEY,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  TOWN VARCHAR(36) NOT NULL,
  SERVICE VARCHAR(30) NOT NULL,
  PHONE_NUMBER INT(20),
  BIRTH_DATE  VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  REG_NAT VARCHAR(100) NOT NULL,
  GENDER CHAR(1) NOT NULL,
  ENABLED BOOLEAN not null default true,
  ROLE VARCHAR(30) NOT NULL
);

create table AUTHORITIES (
	EMAIL varchar(50) not null,
	AUTHORITY varchar(50) not null
);

CREATE TABLE SERVICE (
  SERVICE_ID char(36) PRIMARY KEY,
  SERVICE_NAME VARCHAR(30) NOT NULL,
  SERVICE_TOWN VARCHAR(30) NOT NULL
);

CREATE TABLE TOWN (
TOWN_ID char(36) PRIMARY KEY,
TOWN_NAME VARCHAR(30) NOT NULL,
TOWN_LANGUAGE VARCHAR(30) NOT NULL,
POSTAL_CODE INT(8) NOT NULL,
COUNTRY VARCHAR(30) NOT NULL
);

CREATE TABLE COMPANY (
COMPANY_NAME VARCHAR(40) NOT NULL,
COMPANY_ADDRESS VARCHAR(100) NOT NULL,
COMPANY_VAT_NR VARCHAR(30) PRIMARY KEY,
COMPANY_PHONE VARCHAR(20),
COMPANY_TOWN VARCHAR(30) NOT NULL,
COMPANY_ADMINISTRATOR CHAR(36) NOT NULL
);

CREATE TABLE OFFICIAL_DOC (
DOCUMENT_ID CHAR(36) PRIMARY KEY,
DOCUMENT_DATE CHAR(10) NOT NULL,
DOCUMENT_BENEFICIARY CHAR(36) NOT NULL,
DOCUMENT_ISSUER_SEVICE VARCHAR(30) NOT NULL,
DOCUMENT_ISSUER_TOWN VARCHAR(30) NOT NULL,
DOCUMENT_TRACKING CHAR(36) NOT NULL,
DOCUMENT_EXPIRY CHAR(10)
);

CREATE TABLE DEMAND (
DEMAND_ID CHAR(36) PRIMARY KEY,
CREATION_DATE CHAR(10) NOT NULL,
SENDING_DATE CHAR(10),
CREATOR CHAR(36) NOT NULL,
VERIFICATOR CHAR(36),
SIGNED_BY_CREATOR BIT NOT NULL,
SIGNED_BY_VERIFICATOR BIT NOT NULL,
ACCEPTED BIT NOT NULL,
VERIFICATION_DATE CHAR(10)

);

CREATE TABLE COMPANY_EMPLOYEE (
COMPANY_VAT_NR VARCHAR(30) NOT NULL,
EMPLOYEE_ID CHAR(36) NOT NULL
);

CREATE TABLE COMPANY_ADMINISTRATOR (
COMPANY_VAT_NR VARCHAR(30) NOT NULL,
ADMIN_ID CHAR(36) NOT NULL
);


INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('b6d71f3b-abc3-4343-9194-badd9a882784','LESSINES','FR',7860,'BE');
INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('bd4c7ef2-77b7-457d-8ba1-370673ce1a7a','MONS','FR',7000,'BE');
INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('02ff9254-53ab-461e-a372-d8aa9695db5d','DINANT','FR',5500,'BE');
INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('2af7c53c-d43a-4912-8a77-97af82fb020c','LA ROCHE','FR',6980,'BE');
INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('38e31b98-c42d-4967-9ca8-127abf8785bf','ENGHIEN','FR',7850,'BE');
INSERT INTO TOWN (TOWN_ID,TOWN_NAME,TOWN_LANGUAGE,POSTAL_CODE,COUNTRY)
VALUES ('a7e39b8a-595a-4a65-a5ed-aa99073b765b','BOUSVAL','FR',1470,'BE');

