CREATE DATABASE LABOIL;

USE LABOIL;

CREATE TABLE USER (
  USER_ID      CHAR(36) PRIMARY KEY,
  FIRST_NAME   VARCHAR(30)  NOT NULL,
  LAST_NAME    VARCHAR(30)  NOT NULL,
  ADDRESS      VARCHAR(100) NOT NULL,
  PHONE_NUMBER INT(20),
  BIRTH_DATE   VARCHAR(100) NOT NULL,
  EMAIL        VARCHAR(255) NOT NULL,
  PASSWORD     VARCHAR(100) NOT NULL,
  REG_NAT      VARCHAR(100) NOT NULL,
  ENABLED      BOOLEAN      not null default true
);

CREATE TABLE CITIZEN (
  CITIZEN_ID CHAR(36) PRIMARY KEY,
  USER_ID    CHAR(36)    NOT NULL,
  TOWN       VARCHAR(36) NOT NULL
);

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID CHAR(36) PRIMARY KEY,
  USER_ID     CHAR(36) NOT NULL,
  SERVICE_ID  CHAR(36) NOT NULL
);

create table ROLE (
  EMAIL varchar(50) not null,
  RIGHTS varchar(50) not null
);

CREATE TABLE SERVICE (
  SERVICE_ID    char(36) PRIMARY KEY,
  NAME          VARCHAR(30)  NOT NULL,
  TOWN          CHAR(36)     NOT NULL,
  ADMINISTRATOR CHAR(36)     NOT NULL,
  ADDRESS       VARCHAR(255) NOT NULL
);

CREATE TABLE TOWN (
  TOWN_ID       char(36) PRIMARY KEY,
  NAME          VARCHAR(30)  NOT NULL,
  TOWN_LANGUAGE VARCHAR(30)  NOT NULL,
  POSTAL_CODE   INT(8)       NOT NULL,
  COUNTRY       VARCHAR(30)  NOT NULL,
  ADDRESS       VARCHAR(30)  NOT NULL,
  EMAIL         VARCHAR(255) NOT NULL,
  PHONE_NUMBER  VARCHAR(30)  NOT NULL,
  LOGO_PATH     VARCHAR(255) NOT NULL
);

CREATE TABLE OFFICIAL_DOC (
  DOCUMENT_ID   CHAR(36) PRIMARY KEY,
  CREATION_DATE CHAR(10)     NOT NULL,
  PATH          VARCHAR(255) NOT NULL,
  DEMAND_ID     CHAR(36)     NOT NULL
);

CREATE TABLE DEMAND (
  DEMAND_ID   CHAR(36) PRIMARY KEY,
  NAME        VARCHAR(255) NOT NULL,
  SERVICE_ID  CHAR(36)     NOT NULL,
  CREATOR     CHAR(36)     NOT NULL,
  VERIFICATOR CHAR(36)
);

CREATE TABLE EVENT (
  EVENT_ID      CHAR(36) PRIMARY KEY,
  USER_ID       CHAR(36)     NOT NULL,
  COMMENT       VARCHAR(255) NOT NULL,
  DEMAND_ID     CHAR(36)     NOT NULL,
  STATUS        VARCHAR(20)  NOT NULL,
  CREATION_DATE DATE         NOT NULL
);

CREATE TABLE DEMAND_INFO (
  DEMAND_INFO_ID CHAR(36) PRIMARY KEY,
  DEMAND_ID      CHAR(36)     NOT NULL,
  INFO_KEY       VARCHAR(255) NOT NULL,
  INFO_VALUE     VARCHAR(255) NOT NULL
);

CREATE TABLE LINK_DOCUMENT (
  LINK_DOCUMENT_ID CHAR(36) PRIMARY KEY,
  DEMAND_ID        CHAR(36)     NOT NULL,
  PATH             VARCHAR(255) NOT NULL,
  NAME             VARCHAR(255) NOT NULL
);


INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('b6d71f3b-abc3-4343-9194-badd9a882784', 'LESSINES', 'FR', 7860, 'BE', 'ADDRESS LESSINES', 'LESSINES@be.be', '123456789', 'C:\\DEV\\logo.jpg');
INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('bd4c7ef2-77b7-457d-8ba1-370673ce1a7a', 'MONS', 'FR', 7000, 'BE', 'ADDRESS MONS', 'MONS@be.be', '123456789', 'C:\\DEV\\logo.jpg');
INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('02ff9254-53ab-461e-a372-d8aa9695db5d', 'DINANT', 'FR', 5500, 'BE', 'ADDRESS DINANT', 'DINANT@be.be', '123456789', 'C:\\DEV\\logo.jpg');
INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('2af7c53c-d43a-4912-8a77-97af82fb020c', 'LA ROCHE', 'FR', 6980, 'BE', 'ADDRESS LA ROCHE', 'LAROCHE@be.be', '123456789', 'C:\\DEV\\logo.jpg');
INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('38e31b98-c42d-4967-9ca8-127abf8785bf', 'ENGHIEN', 'FR', 7850, 'BE', 'ADDRESS ENGHIEN', 'ENGHIEN@be.be', '123456789', 'C:\\DEV\\logo.jpg');
INSERT INTO TOWN (TOWN_ID, NAME, TOWN_LANGUAGE, POSTAL_CODE, COUNTRY, ADDRESS, EMAIL, PHONE_NUMBER, LOGO_PATH)
VALUES ('a7e39b8a-595a-4a65-a5ed-aa99073b765b', 'BOUSVAL', 'FR', 1470, 'BE', 'ADDRESS BOUSVAL', 'BOUSVAL@be.be', '123456789', 'C:\\DEV\\logo.jpg');

